// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD_ItHFZNjRYbcQpOvpG2umjiH_3QpnF8',
    appId: '1:844549726999:web:5814d45913d4e020210d52',
    messagingSenderId: '844549726999',
    projectId: 'zad-app-2024',
    authDomain: 'zad-app-2024.firebaseapp.com',
    storageBucket: 'zad-app-2024.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADRdXiPayV-7I8a1adxjSFYBYrE59I-uk',
    appId: '1:844549726999:android:23d5a176f04488b9210d52',
    messagingSenderId: '844549726999',
    projectId: 'zad-app-2024',
    storageBucket: 'zad-app-2024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNAKVy30D0j-nF0DFMKo6brxdhEKHlSDQ',
    appId: '1:844549726999:ios:80400ed627665653210d52',
    messagingSenderId: '844549726999',
    projectId: 'zad-app-2024',
    storageBucket: 'zad-app-2024.firebasestorage.app',
    iosBundleId: 'com.example.zad',
  );

}